version: '3.8'
services:
  #Postgresql video-rental service
  postgresql_video_rental_service:
    container_name: postgresql_video_rental_service
    image: postgres:latest
    environment:
      - POSTGRES_DB=video-rental
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "10088:5432"
    volumes:
      - db_video_rental_service:/var/lib/postgresql/data
    restart: unless-stopped

#Named volumes
volumes:
  db_video_rental_service:
    driver: local